### ISSUE TITLE
unknown type name 'LiquidCrystal'

### ISSUE THREAD

**Issue by luclaurent** [RobotShop/Wheatstone-Bridge-Amplifier-Shield#1]
I am trying to compile your code `strain_gauge_shield_and_lcd_arduino_uno_code.ino` in my arduino IDE (version 1.6.8) without doing any modification. I obtain the following error:

> unknown type name 'LiquidCrystal'

This error seems to come from the header file and the line: 

> extern LiquidCrystal lcd;

**Log**

> Arduino : 1.6.8 (Mac OS X), Carte : "Arduino/Genuino Uno"
> Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware "/Applications/Arduino.app/Contents/Java/hardware" -tools "/Applications/Arduino.app/Contents/Java/tools-builder" -tools "/Applications/Arduino.app/Contents/Java/hardware/tools/avr" -built-in-libraries "/Applications/Arduino.app/Contents/Java/libraries" -libraries "/Users/xxxx/Documents/Arduino/libraries" -fqbn=arduino:avr:uno -ide-version=10608 -build-path "/var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "/Users/xxxx/Documents/Arduino/strain_gauge_shield_and_lcd_arduino_uno_code/strain_gauge_shield_and_lcd_arduino_uno_code.ino"
> /Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware "/Applications/Arduino.app/Contents/Java/hardware" -tools "/Applications/Arduino.app/Contents/Java/tools-builder" -tools "/Applications/Arduino.app/Contents/Java/hardware/tools/avr" -built-in-libraries "/Applications/Arduino.app/Contents/Java/libraries" -libraries "/Users/xxxx/Documents/Arduino/libraries" -fqbn=arduino:avr:uno -ide-version=10608 -build-path "/var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "/Users/xxxx/Documents/Arduino/strain_gauge_shield_and_lcd_arduino_uno_code/strain_gauge_shield_and_lcd_arduino_uno_code.ino"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "/var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd_arduino_uno_code.ino.cpp" -o "/dev/null"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "/var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c" -o "/dev/null"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Users/xxxx/Documents/Arduino/libraries/Wheatstone-Bridge-Amplifier-Shield" "/var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c" -o "/dev/null"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Users/xxxx/Documents/Arduino/libraries/Wheatstone-Bridge-Amplifier-Shield" "-I/Applications/Arduino.app/Contents/Java/libraries/LiquidCrystal/src" "/var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c" -o "/dev/null"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Users/xxxx/Documents/Arduino/libraries/Wheatstone-Bridge-Amplifier-Shield" "-I/Applications/Arduino.app/Contents/Java/libraries/LiquidCrystal/src" "/var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd_arduino_uno_code.ino.cpp" -o "/dev/null"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Users/xxxx/Documents/Arduino/libraries/Wheatstone-Bridge-Amplifier-Shield" "-I/Applications/Arduino.app/Contents/Java/libraries/LiquidCrystal/src" "/Users/xxxx/Documents/Arduino/libraries/Wheatstone-Bridge-Amplifier-Shield/WheatstoneBridge.cpp" -o "/dev/null"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Users/xxxx/Documents/Arduino/libraries/Wheatstone-Bridge-Amplifier-Shield" "-I/Applications/Arduino.app/Contents/Java/libraries/LiquidCrystal/src" "/Applications/Arduino.app/Contents/Java/libraries/LiquidCrystal/src/LiquidCrystal.cpp" -o "/dev/null"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Users/xxxx/Documents/Arduino/libraries/Wheatstone-Bridge-Amplifier-Shield" "-I/Applications/Arduino.app/Contents/Java/libraries/LiquidCrystal/src" "/var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd_arduino_uno_code.ino.cpp" -o "/var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/preproc/ctags_target_for_gcc_minus_e.cpp"
> "/Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino10/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "/var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/preproc/ctags_target_for_gcc_minus_e.cpp"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc" -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "-I/Users/xxxx/Documents/Arduino/libraries/Wheatstone-Bridge-Amplifier-Shield" "-I/Applications/Arduino.app/Contents/Java/libraries/LiquidCrystal/src" "/var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c" -o "/var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c.o"
> In file included from /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd_support_functions.h:2:0,
>                  from /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c:2:
> /Users/xxxx/Documents/Arduino/libraries/Wheatstone-Bridge-Amplifier-Shield/WheatstoneBridge.h:24:1: error: unknown type name 'class'
>  class WheatstoneBridge
>  ^
> /Users/xxxx/Documents/Arduino/libraries/Wheatstone-Bridge-Amplifier-Shield/WheatstoneBridge.h:25:1: error: expected '=', ',', ';', 'asm' or '**attribute**' before '{' token
>  {
>  ^
> In file included from /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.h:27:0,
>                  from /Applications/Arduino.app/Contents/Java/libraries/LiquidCrystal/src/LiquidCrystal.h:5,
>                  from /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd_support_functions.h:5,
>                  from /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c:2:
> /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Printable.h:25:1: error: unknown type name 'class'
>  class Print;
>  ^
> /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Printable.h:33:1: error: unknown type name 'class'
>  class Printable
>  ^
> /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Printable.h:34:1: error: expected '=', ',', ';', 'asm' or '**attribute**' before '{' token
>  {
>  ^
> In file included from /Applications/Arduino.app/Contents/Java/libraries/LiquidCrystal/src/LiquidCrystal.h:5:0,
>                  from /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd_support_functions.h:5,
>                  from /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c:2:
> /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.h:34:1: error: unknown type name 'class'
>  class Print
>  ^
> /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.h:35:1: error: expected '=', ',', ';', 'asm' or '**attribute**' before '{' token
>  {
>  ^
> In file included from /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd_support_functions.h:5:0,
>                  from /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c:2:
> /Applications/Arduino.app/Contents/Java/libraries/LiquidCrystal/src/LiquidCrystal.h:45:1: error: unknown type name 'class'
>  class LiquidCrystal : public Print {
>  ^
> /Applications/Arduino.app/Contents/Java/libraries/LiquidCrystal/src/LiquidCrystal.h:45:21: error: expected '=', ',', ';', 'asm' or '**attribute**' before ':' token
>  class LiquidCrystal : public Print {
>                      ^
> In file included from /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c:2:0:
> strain_gauge_shield_and_lcd_support_functions.h:8: error: unknown type name 'LiquidCrystal'
>  extern LiquidCrystal lcd;
>  ^
> /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c: In function 'displayScreen':
> strain_gauge_shield_and_lcd__support_functions.c:35: error: request for member 'clear' in something not a structure or union
>    lcd.clear();
>       ^
> strain_gauge_shield_and_lcd__support_functions.c:36: error: request for member 'setCursor' in something not a structure or union
>    lcd.setCursor(0,0); lcd.print(row1);
>       ^
> strain_gauge_shield_and_lcd__support_functions.c:36: error: request for member 'print' in something not a structure or union
>    lcd.setCursor(0,0); lcd.print(row1);
>                           ^
> strain_gauge_shield_and_lcd__support_functions.c:37: error: request for member 'setCursor' in something not a structure or union
>    lcd.setCursor(0,1); lcd.print(row2);
>       ^
> strain_gauge_shield_and_lcd__support_functions.c:37: error: request for member 'print' in something not a structure or union
>    lcd.setCursor(0,1); lcd.print(row2);
>                           ^
> strain_gauge_shield_and_lcd__support_functions.c:38: error: 'Serial' undeclared (first use in this function)
>    Serial.println(""); Serial.println(row1); Serial.println(row2);
>    ^
> /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c:38:3: note: each undeclared identifier is reported only once for each function it appears in
> /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c: At top level:
> strain_gauge_shield_and_lcd__support_functions.c:42: error: expected ';', ',' or ')' before '=' token
>  void waitSelect(bool disp = false)
>                            ^
> /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c: In function 'getValueADC':
> strain_gauge_shield_and_lcd__support_functions.c:72: error: request for member 'setCursor' in something not a structure or union
>        lcd.setCursor(pos, 1); lcd.print("                ");
>           ^
> strain_gauge_shield_and_lcd__support_functions.c:72: error: request for member 'print' in something not a structure or union
>        lcd.setCursor(pos, 1); lcd.print("                ");
>                                  ^
> strain_gauge_shield_and_lcd__support_functions.c:73: error: request for member 'setCursor' in something not a structure or union
>        lcd.setCursor(pos, 1); lcd.print(value);
>           ^
> strain_gauge_shield_and_lcd__support_functions.c:73: error: request for member 'print' in something not a structure or union
>        lcd.setCursor(pos, 1); lcd.print(value);
>                                  ^
> strain_gauge_shield_and_lcd__support_functions.c:74: error: 'Serial' undeclared (first use in this function)
>        Serial.println(""); Serial.println(row1); Serial.print(row2); Serial.print(" "); Serial.println(value);
>        ^
> /var/folders/07/wjqwh1hj54106pwllgth4pfc0000gn/T/build3d9e50a6c4e54aac3cbd7143ae1ab14a.tmp/sketch/strain_gauge_shield_and_lcd__support_functions.c: In function 'getValueInRange':
> strain_gauge_shield_and_lcd__support_functions.c:127: error: request for member 'setCursor' in something not a structure or union
>        lcd.setCursor(pos, 1); lcd.print("                ");
>           ^
> strain_gauge_shield_and_lcd__support_functions.c:127: error: request for member 'print' in something not a structure or union
>        lcd.setCursor(pos, 1); lcd.print("                ");
>                                  ^
> strain_gauge_shield_and_lcd__support_functions.c:128: error: request for member 'setCursor' in something not a structure or union
>        lcd.setCursor(pos, 1); lcd.print(value);
>           ^
> strain_gauge_shield_and_lcd__support_functions.c:128: error: request for member 'print' in something not a structure or union
>        lcd.setCursor(pos, 1); lcd.print(value);
>                                  ^
> strain_gauge_shield_and_lcd__support_functions.c:129: error: 'Serial' undeclared (first use in this function)
>        Serial.println(""); Serial.println(row1); Serial.print(row2); Serial.print(" "); Serial.println(value);
>        ^
> Utilisation de la bibliothèque Wheatstone-Bridge-Amplifier-Shield prise dans le dossier : /Users/xxxx/Documents/Arduino/libraries/Wheatstone-Bridge-Amplifier-Shield (legacy)
> Utilisation de la bibliothèque LiquidCrystal version 1.0.5 dans le dossier: /Applications/Arduino.app/Contents/Java/libraries/LiquidCrystal 
> exit status 1
> unknown type name 'LiquidCrystal'

**Comment by luclaurent** [comment]
In fact this error is due to a wrong extension of the `strain_gauge_shield_and_lcd__support_functions.c` file. The use of a `.cpp` solves the problem.

**Comment by RobotShop** [comment]
Good catch! It appears the filename extension was changed in a commit on 2016-03-04. It is now changed back to .cpp and everything seems to compile properly.
Thanks!
